using System;
using System.Collections.Generic;
using System.IO;
using System.Windows.Forms;
using HoI2Editor.Parsers;
using HoI2Editor.Properties;
using HoI2Editor.Writers;

namespace HoI2Editor.Models
{
    /// <summary>
    ///     ユニットデータ群
    /// </summary>
    public static class Units
    {
        /// <summary>
        ///     ユニット群
        /// </summary>
        public static List<Unit> List;

        /// <summary>
        ///     ユニット種類文字列とIDの対応付け
        /// </summary>
        public static readonly Dictionary<string, UnitType> StringMap = new Dictionary<string, UnitType>();

        /// <summary>
        ///     ユニット種類文字列テーブル
        /// </summary>
        public static readonly string[] StringTable =
            {
                "infantry",
                "cavalry",
                "motorized",
                "mechanized",
                "light_armor",
                "armor",
                "garrison",
                "hq",
                "paratrooper",
                "marine",
                "bergsjaeger",
                "cas",
                "multi_role",
                "interceptor",
                "strategic_bomber",
                "tactical_bomber",
                "naval_bomber",
                "transport_plane",
                "battleship",
                "light_cruiser",
                "heavy_cruiser",
                "battlecruiser",
                "destroyer",
                "carrier",
                "submarine",
                "transport",
                "flying_bomb",
                "flying_rocket",
                "militia",
                "escort_carrier",
                "nuclear_submarine",
                "light_carrier",
                "rocket_interceptor",
                "d_rsv_33",
                "d_rsv_34",
                "d_rsv_35",
                "d_rsv_36",
                "d_rsv_37",
                "d_rsv_38",
                "d_rsv_39",
                "d_rsv_40",
                "d_01",
                "d_02",
                "d_03",
                "d_04",
                "d_05",
                "d_06",
                "d_07",
                "d_08",
                "d_09",
                "d_10",
                "d_11",
                "d_12",
                "d_13",
                "d_14",
                "d_15",
                "d_16",
                "d_17",
                "d_18",
                "d_19",
                "d_20",
                "d_21",
                "d_22",
                "d_23",
                "d_24",
                "d_25",
                "d_26",
                "d_27",
                "d_28",
                "d_29",
                "d_30",
                "d_31",
                "d_32",
                "d_33",
                "d_34",
                "d_35",
                "d_36",
                "d_37",
                "d_38",
                "d_39",
                "d_40",
                "d_41",
                "d_42",
                "d_43",
                "d_44",
                "d_45",
                "d_46",
                "d_47",
                "d_48",
                "d_49",
                "d_50",
                "d_51",
                "d_52",
                "d_53",
                "d_54",
                "d_55",
                "d_56",
                "d_57",
                "d_58",
                "d_59",
                "d_60",
                "d_61",
                "d_62",
                "d_63",
                "d_64",
                "d_65",
                "d_66",
                "d_67",
                "d_68",
                "d_69",
                "d_70",
                "d_71",
                "d_72",
                "d_73",
                "d_74",
                "d_75",
                "d_76",
                "d_77",
                "d_78",
                "d_79",
                "d_80",
                "d_81",
                "d_82",
                "d_83",
                "d_84",
                "d_85",
                "d_86",
                "d_87",
                "d_88",
                "d_89",
                "d_90",
                "d_91",
                "d_92",
                "d_93",
                "d_94",
                "d_95",
                "d_96",
                "d_97",
                "d_98",
                "d_99",
                "none",
                "artillery",
                "sp_artillery",
                "rocket_artillery",
                "sp_rct_artillery",
                "anti_tank",
                "tank_destroyer",
                "light_armor_brigade",
                "heavy_armor",
                "super_heavy_armor",
                "armored_car",
                "anti_air",
                "police",
                "engineer",
                "cag",
                "escort",
                "naval_asw",
                "naval_anti_air_s",
                "naval_radar_s",
                "naval_fire_controll_s",
                "naval_improved_hull_s",
                "naval_torpedoes_s",
                "naval_anti_air_l",
                "naval_radar_l",
                "naval_fire_controll_l",
                "naval_improved_hull_l",
                "naval_torpedoes_l",
                "b_u1",
                "b_u2",
                "b_u3",
                "b_u4",
                "b_u5",
                "b_u6",
                "b_u7",
                "b_u8",
                "b_u9",
                "b_u10",
                "b_u11",
                "b_u12",
                "b_u13",
                "b_u14",
                "b_u15",
                "b_u16",
                "b_u17",
                "b_u18",
                "b_u19",
                "b_u20",
                "cavalry_brigade",
                "sp_anti_air",
                "medium_armor",
                "floatplane",
                "light_cag",
                "amph_armor",
                "glider_armor",
                "glider_artillery",
                "super_heavy_artillery",
                "b_rsv_36",
                "b_rsv_37",
                "b_rsv_38",
                "b_rsv_39",
                "b_rsv_40",
                "b_01",
                "b_02",
                "b_03",
                "b_04",
                "b_05",
                "b_06",
                "b_07",
                "b_08",
                "b_09",
                "b_10",
                "b_11",
                "b_12",
                "b_13",
                "b_14",
                "b_15",
                "b_16",
                "b_17",
                "b_18",
                "b_19",
                "b_20",
                "b_21",
                "b_22",
                "b_23",
                "b_24",
                "b_25",
                "b_26",
                "b_27",
                "b_28",
                "b_29",
                "b_30",
                "b_31",
                "b_32",
                "b_33",
                "b_34",
                "b_35",
                "b_36",
                "b_37",
                "b_38",
                "b_39",
                "b_40",
                "b_41",
                "b_42",
                "b_43",
                "b_44",
                "b_45",
                "b_46",
                "b_47",
                "b_48",
                "b_49",
                "b_50",
                "b_51",
                "b_52",
                "b_53",
                "b_54",
                "b_55",
                "b_56",
                "b_57",
                "b_58",
                "b_59",
                "b_60",
                "b_61",
                "b_62",
                "b_63",
                "b_64",
                "b_65",
                "b_66",
                "b_67",
                "b_68",
                "b_69",
                "b_70",
                "b_71",
                "b_72",
                "b_73",
                "b_74",
                "b_75",
                "b_76",
                "b_77",
                "b_78",
                "b_79",
                "b_80",
                "b_81",
                "b_82",
                "b_83",
                "b_84",
                "b_85",
                "b_86",
                "b_87",
                "b_88",
                "b_89",
                "b_90",
                "b_91",
                "b_92",
                "b_93",
                "b_94",
                "b_95",
                "b_96",
                "b_97",
                "b_98",
                "b_99"
            };

        /// <summary>
        ///     生産ユニット種類文字列テーブル
        /// </summary>
        public static readonly string[] RealStringTable =
            {
                "infantry",
                "cavalry",
                "motorized",
                "mechanized",
                "light_armor",
                "armor",
                "garrison",
                "hq",
                "paratrooper",
                "marine",
                "bergsjaeger",
                "cas",
                "multi_role",
                "interceptor",
                "strategic_bomber",
                "tactical_bomber",
                "naval_bomber",
                "transport_plane",
                "battleship",
                "light_cruiser",
                "heavy_cruiser",
                "battlecruiser",
                "destroyer",
                "carrier",
                "submarine",
                "transport",
                "flying_bomb",
                "flying_rocket",
                "militia",
                "escort_carrier",
                "nuclear_submarine"
            };

        /// <summary>
        ///     スプライト種類文字列テーブル
        /// </summary>
        public static readonly string[] SpriteStringTable =
            {
                "infantry",
                "cavalry",
                "motorized",
                "mechanized",
                "l_panzer",
                "panzer",
                "paratrooper",
                "marine",
                "bergsjaeger",
                "fighter",
                "escort",
                "interceptor",
                "bomber",
                "tactical",
                "cas",
                "naval",
                "transportplane",
                "battleship",
                "battlecruiser",
                "heavy_cruiser",
                "light_cruiser",
                "destroyer",
                "carrier",
                "submarine",
                "transport",
                "militia",
                "garrison",
                "hq",
                "flying_bomb",
                "rocket",
                "nuclear_submarine",
                "escort_carrier",
                "light_carrier",
                "rocket_interceptor",
                "d_rsv_33",
                "d_rsv_34",
                "d_rsv_35",
                "d_rsv_36",
                "d_rsv_37",
                "d_rsv_38",
                "d_rsv_39",
                "d_rsv_40",
                "d_01",
                "d_02",
                "d_03",
                "d_04",
                "d_05",
                "d_06",
                "d_07",
                "d_08",
                "d_09",
                "d_10",
                "d_11",
                "d_12",
                "d_13",
                "d_14",
                "d_15",
                "d_16",
                "d_17",
                "d_18",
                "d_19",
                "d_20",
                "d_21",
                "d_22",
                "d_23",
                "d_24",
                "d_25",
                "d_26",
                "d_27",
                "d_28",
                "d_29",
                "d_30",
                "d_31",
                "d_32",
                "d_33",
                "d_34",
                "d_35",
                "d_36",
                "d_37",
                "d_38",
                "d_39",
                "d_40",
                "d_41",
                "d_42",
                "d_43",
                "d_44",
                "d_45",
                "d_46",
                "d_47",
                "d_48",
                "d_49",
                "d_50",
                "d_51",
                "d_52",
                "d_53",
                "d_54",
                "d_55",
                "d_56",
                "d_57",
                "d_58",
                "d_59",
                "d_60",
                "d_61",
                "d_62",
                "d_63",
                "d_64",
                "d_65",
                "d_66",
                "d_67",
                "d_68",
                "d_69",
                "d_70",
                "d_71",
                "d_72",
                "d_73",
                "d_74",
                "d_75",
                "d_76",
                "d_77",
                "d_78",
                "d_79",
                "d_80",
                "d_81",
                "d_82",
                "d_83",
                "d_84",
                "d_85",
                "d_86",
                "d_87",
                "d_88",
                "d_89",
                "d_90",
                "d_91",
                "d_92",
                "d_93",
                "d_94",
                "d_95",
                "d_96",
                "d_97",
                "d_98",
                "d_99"
            };

        /// <summary>
        ///     ユニット一覧
        /// </summary>
        public static UnitType[] UnitTable;

        /// <summary>
        ///     ユニット一覧 (HoI2)
        /// </summary>
        private static readonly UnitType[] UnitTableHoI2 =
            {
                // 師団
                UnitType.Infantry,
                UnitType.Cavalry,
                UnitType.Motorized,
                UnitType.Mechanized,
                UnitType.LightArmor,
                UnitType.Armor,
                UnitType.Garrison,
                UnitType.Hq,
                UnitType.Paratrooper,
                UnitType.Marine,
                UnitType.Bergsjaeger,
                UnitType.Cas,
                UnitType.MultiRole,
                UnitType.Interceptor,
                UnitType.StrategicBomber,
                UnitType.TacticalBomber,
                UnitType.NavalBomber,
                UnitType.TransportPlane,
                UnitType.BattleShip,
                UnitType.LightCruiser,
                UnitType.HeavyCruiser,
                UnitType.BattleCruiser,
                UnitType.Destroyer,
                UnitType.Carrier,
                UnitType.Submarine,
                UnitType.Transport,
                UnitType.FlyingBomb,
                UnitType.FlyingRocket,
                UnitType.Militia,
                UnitType.EscortCarrier,
                UnitType.NuclearSubmarine,

                // 旅団
                UnitType.None,
                UnitType.Artillery,
                UnitType.SpArtillery,
                UnitType.RocketArtillery,
                UnitType.SpRctArtillery,
                UnitType.AntiTank,
                UnitType.TankDestroyer,
                UnitType.LightArmorBrigade,
                UnitType.HeavyArmor,
                UnitType.SuperHeavyArmor,
                UnitType.ArmoredCar,
                UnitType.AntiAir,
                UnitType.Police,
                UnitType.Engineer,
                UnitType.Cag,
                UnitType.Escort,
                UnitType.NavalAsw,
                UnitType.NavalAntiAirS,
                UnitType.NavalRadarS,
                UnitType.NavalFireControllS,
                UnitType.NavalImprovedHullS,
                UnitType.NavalTorpedoesS,
                UnitType.NavalAntiAirL,
                UnitType.NavalRadarL,
                UnitType.NavalFireControllL,
                UnitType.NavalImprovedHullL,
                UnitType.NavalTorpedoesL
            };

        /// <summary>
        ///     ユニット一覧 (AoD)
        /// </summary>
        private static readonly UnitType[] UnitTableAoD =
            {
                // 師団
                UnitType.Infantry,
                UnitType.Cavalry,
                UnitType.Motorized,
                UnitType.Mechanized,
                UnitType.LightArmor,
                UnitType.Armor,
                UnitType.Garrison,
                UnitType.Hq,
                UnitType.Paratrooper,
                UnitType.Marine,
                UnitType.Bergsjaeger,
                UnitType.Cas,
                UnitType.MultiRole,
                UnitType.Interceptor,
                UnitType.StrategicBomber,
                UnitType.TacticalBomber,
                UnitType.NavalBomber,
                UnitType.TransportPlane,
                UnitType.BattleShip,
                UnitType.LightCruiser,
                UnitType.HeavyCruiser,
                UnitType.BattleCruiser,
                UnitType.Destroyer,
                UnitType.Carrier,
                UnitType.Submarine,
                UnitType.Transport,
                UnitType.FlyingBomb,
                UnitType.FlyingRocket,
                UnitType.Militia,
                UnitType.EscortCarrier,
                UnitType.NuclearSubmarine,

                // 旅団
                UnitType.None,
                UnitType.Artillery,
                UnitType.SpArtillery,
                UnitType.RocketArtillery,
                UnitType.SpRctArtillery,
                UnitType.AntiTank,
                UnitType.TankDestroyer,
                UnitType.LightArmorBrigade,
                UnitType.HeavyArmor,
                UnitType.SuperHeavyArmor,
                UnitType.ArmoredCar,
                UnitType.AntiAir,
                UnitType.Police,
                UnitType.Engineer,
                UnitType.Cag,
                UnitType.Escort,
                UnitType.NavalAsw,
                UnitType.NavalAntiAirS,
                UnitType.NavalRadarS,
                UnitType.NavalFireControllS,
                UnitType.NavalImprovedHullS,
                UnitType.NavalTorpedoesS,
                UnitType.NavalAntiAirL,
                UnitType.NavalRadarL,
                UnitType.NavalFireControllL,
                UnitType.NavalImprovedHullL,
                UnitType.NavalTorpedoesL,
                UnitType.Bu1,
                UnitType.Bu2,
                UnitType.Bu3,
                UnitType.Bu4,
                UnitType.Bu5,
                UnitType.Bu6,
                UnitType.Bu7,
                UnitType.Bu8,
                UnitType.Bu9,
                UnitType.Bu10,
                UnitType.Bu11,
                UnitType.Bu12,
                UnitType.Bu13,
                UnitType.Bu14,
                UnitType.Bu15,
                UnitType.Bu16,
                UnitType.Bu17,
                UnitType.Bu18,
                UnitType.Bu19,
                UnitType.Bu20
            };

        /// <summary>
        ///     ユニット一覧 (DH1.03以降)
        /// </summary>
        private static readonly UnitType[] UnitTableDh =
            {
                // 師団
                UnitType.Infantry,
                UnitType.Cavalry,
                UnitType.Motorized,
                UnitType.Mechanized,
                UnitType.LightArmor,
                UnitType.Armor,
                UnitType.Garrison,
                UnitType.Hq,
                UnitType.Paratrooper,
                UnitType.Marine,
                UnitType.Bergsjaeger,
                UnitType.Cas,
                UnitType.MultiRole,
                UnitType.Interceptor,
                UnitType.StrategicBomber,
                UnitType.TacticalBomber,
                UnitType.NavalBomber,
                UnitType.TransportPlane,
                UnitType.BattleShip,
                UnitType.LightCruiser,
                UnitType.HeavyCruiser,
                UnitType.BattleCruiser,
                UnitType.Destroyer,
                UnitType.Carrier,
                UnitType.Submarine,
                UnitType.Transport,
                UnitType.FlyingBomb,
                UnitType.FlyingRocket,
                UnitType.Militia,
                UnitType.EscortCarrier,
                UnitType.NuclearSubmarine,
                UnitType.LightCarrier,
                UnitType.RocketInterceptor,
                UnitType.ReserveDivision33,
                UnitType.ReserveDivision34,
                UnitType.ReserveDivision35,
                UnitType.ReserveDivision36,
                UnitType.ReserveDivision37,
                UnitType.ReserveDivision38,
                UnitType.ReserveDivision39,
                UnitType.ReserveDivision40,
                UnitType.Division01,
                UnitType.Division02,
                UnitType.Division03,
                UnitType.Division04,
                UnitType.Division05,
                UnitType.Division06,
                UnitType.Division07,
                UnitType.Division08,
                UnitType.Division09,
                UnitType.Division10,
                UnitType.Division11,
                UnitType.Division12,
                UnitType.Division13,
                UnitType.Division14,
                UnitType.Division15,
                UnitType.Division16,
                UnitType.Division17,
                UnitType.Division18,
                UnitType.Division19,
                UnitType.Division20,
                UnitType.Division21,
                UnitType.Division22,
                UnitType.Division23,
                UnitType.Division24,
                UnitType.Division25,
                UnitType.Division26,
                UnitType.Division27,
                UnitType.Division28,
                UnitType.Division29,
                UnitType.Division30,
                UnitType.Division31,
                UnitType.Division32,
                UnitType.Division33,
                UnitType.Division34,
                UnitType.Division35,
                UnitType.Division36,
                UnitType.Division37,
                UnitType.Division38,
                UnitType.Division39,
                UnitType.Division40,
                UnitType.Division41,
                UnitType.Division42,
                UnitType.Division43,
                UnitType.Division44,
                UnitType.Division45,
                UnitType.Division46,
                UnitType.Division47,
                UnitType.Division48,
                UnitType.Division49,
                UnitType.Division50,
                UnitType.Division51,
                UnitType.Division52,
                UnitType.Division53,
                UnitType.Division54,
                UnitType.Division55,
                UnitType.Division56,
                UnitType.Division57,
                UnitType.Division58,
                UnitType.Division59,
                UnitType.Division60,
                UnitType.Division61,
                UnitType.Division62,
                UnitType.Division63,
                UnitType.Division64,
                UnitType.Division65,
                UnitType.Division66,
                UnitType.Division67,
                UnitType.Division68,
                UnitType.Division69,
                UnitType.Division70,
                UnitType.Division71,
                UnitType.Division72,
                UnitType.Division73,
                UnitType.Division74,
                UnitType.Division75,
                UnitType.Division76,
                UnitType.Division77,
                UnitType.Division78,
                UnitType.Division79,
                UnitType.Division80,
                UnitType.Division81,
                UnitType.Division82,
                UnitType.Division83,
                UnitType.Division84,
                UnitType.Division85,
                UnitType.Division86,
                UnitType.Division87,
                UnitType.Division88,
                UnitType.Division89,
                UnitType.Division90,
                UnitType.Division91,
                UnitType.Division92,
                UnitType.Division93,
                UnitType.Division94,
                UnitType.Division95,
                UnitType.Division96,
                UnitType.Division97,
                UnitType.Division98,
                UnitType.Division99,

                // 旅団
                UnitType.None,
                UnitType.Artillery,
                UnitType.SpArtillery,
                UnitType.RocketArtillery,
                UnitType.SpRctArtillery,
                UnitType.AntiTank,
                UnitType.TankDestroyer,
                UnitType.LightArmorBrigade,
                UnitType.HeavyArmor,
                UnitType.SuperHeavyArmor,
                UnitType.ArmoredCar,
                UnitType.AntiAir,
                UnitType.Police,
                UnitType.Engineer,
                UnitType.Cag,
                UnitType.Escort,
                UnitType.NavalAsw,
                UnitType.NavalAntiAirS,
                UnitType.NavalRadarS,
                UnitType.NavalFireControllS,
                UnitType.NavalImprovedHullS,
                UnitType.NavalTorpedoesS,
                UnitType.NavalAntiAirL,
                UnitType.NavalRadarL,
                UnitType.NavalFireControllL,
                UnitType.NavalImprovedHullL,
                UnitType.NavalTorpedoesL,
                UnitType.CavalryBrigade,
                UnitType.SpAntiAir,
                UnitType.MediumArmor,
                UnitType.FloatPlane,
                UnitType.LightCag,
                UnitType.AmphArmor,
                UnitType.GliderArmor,
                UnitType.GliderArtillery,
                UnitType.SuperHeavyArtillery,
                UnitType.BRsv36,
                UnitType.BRsv37,
                UnitType.BRsv38,
                UnitType.BRsv39,
                UnitType.BRsv40,
                UnitType.B01,
                UnitType.B02,
                UnitType.B03,
                UnitType.B04,
                UnitType.B05,
                UnitType.B06,
                UnitType.B07,
                UnitType.B08,
                UnitType.B09,
                UnitType.B10,
                UnitType.B11,
                UnitType.B12,
                UnitType.B13,
                UnitType.B14,
                UnitType.B15,
                UnitType.B16,
                UnitType.B17,
                UnitType.B18,
                UnitType.B19,
                UnitType.B20,
                UnitType.B21,
                UnitType.B22,
                UnitType.B23,
                UnitType.B24,
                UnitType.B25,
                UnitType.B26,
                UnitType.B27,
                UnitType.B28,
                UnitType.B29,
                UnitType.B30,
                UnitType.B31,
                UnitType.B32,
                UnitType.B33,
                UnitType.B34,
                UnitType.B35,
                UnitType.B36,
                UnitType.B37,
                UnitType.B38,
                UnitType.B39,
                UnitType.B40,
                UnitType.B41,
                UnitType.B42,
                UnitType.B43,
                UnitType.B44,
                UnitType.B45,
                UnitType.B46,
                UnitType.B47,
                UnitType.B48,
                UnitType.B49,
                UnitType.B50,
                UnitType.B51,
                UnitType.B52,
                UnitType.B53,
                UnitType.B54,
                UnitType.B55,
                UnitType.B56,
                UnitType.B57,
                UnitType.B58,
                UnitType.B59,
                UnitType.B60,
                UnitType.B61,
                UnitType.B62,
                UnitType.B63,
                UnitType.B64,
                UnitType.B65,
                UnitType.B66,
                UnitType.B67,
                UnitType.B68,
                UnitType.B69,
                UnitType.B70,
                UnitType.B71,
                UnitType.B72,
                UnitType.B73,
                UnitType.B74,
                UnitType.B75,
                UnitType.B76,
                UnitType.B77,
                UnitType.B78,
                UnitType.B79,
                UnitType.B80,
                UnitType.B81,
                UnitType.B82,
                UnitType.B83,
                UnitType.B84,
                UnitType.B85,
                UnitType.B86,
                UnitType.B87,
                UnitType.B88,
                UnitType.B89,
                UnitType.B90,
                UnitType.B91,
                UnitType.B92,
                UnitType.B93,
                UnitType.B94,
                UnitType.B95,
                UnitType.B96,
                UnitType.B97,
                UnitType.B98,
                UnitType.B99
            };

        /// <summary>
        ///     ユニット定義ファイル名とIDの対応付け
        /// </summary>
        public static Dictionary<UnitType, string> FileNameMap = new Dictionary<UnitType, string>();

        /// <summary>
        ///     デフォルトのユニット定義ファイル名
        /// </summary>
        private static readonly string[] DefaultFileNames =
            {
                "divisions\\infantry.txt",
                "divisions\\cavalry.txt",
                "divisions\\motorized.txt",
                "divisions\\mechanized.txt",
                "divisions\\light_armor.txt",
                "divisions\\armor.txt",
                "divisions\\garrison.txt",
                "divisions\\hq.txt",
                "divisions\\paratrooper.txt",
                "divisions\\marine.txt",
                "divisions\\bergsjaeger.txt",
                "divisions\\cas.txt",
                "divisions\\multi_role.txt",
                "divisions\\interceptor.txt",
                "divisions\\strategic_bomber.txt",
                "divisions\\tactical_bomber.txt",
                "divisions\\naval_bomber.txt",
                "divisions\\transport_plane.txt",
                "divisions\\battleship.txt",
                "divisions\\light_cruiser.txt",
                "divisions\\heavy_cruiser.txt",
                "divisions\\battlecruiser.txt",
                "divisions\\destroyer.txt",
                "divisions\\carrier.txt",
                "divisions\\submarine.txt",
                "divisions\\transport.txt",
                "divisions\\flying_bomb.txt",
                "divisions\\flying_rocket.txt",
                "divisions\\militia.txt",
                "divisions\\escort_carrier.txt",
                "divisions\\nuclear_submarine.txt",
                "divisions\\light_carrier",
                "divisions\\rocket_interceptor",
                "divisions\\d_rsv_33",
                "divisions\\d_rsv_34",
                "divisions\\d_rsv_35",
                "divisions\\d_rsv_36",
                "divisions\\d_rsv_37",
                "divisions\\d_rsv_38",
                "divisions\\d_rsv_39",
                "divisions\\d_rsv_40",
                "divisions\\d_01",
                "divisions\\d_02",
                "divisions\\d_03",
                "divisions\\d_04",
                "divisions\\d_05",
                "divisions\\d_06",
                "divisions\\d_07",
                "divisions\\d_08",
                "divisions\\d_09",
                "divisions\\d_10",
                "divisions\\d_11",
                "divisions\\d_12",
                "divisions\\d_13",
                "divisions\\d_14",
                "divisions\\d_15",
                "divisions\\d_16",
                "divisions\\d_17",
                "divisions\\d_18",
                "divisions\\d_19",
                "divisions\\d_20",
                "divisions\\d_21",
                "divisions\\d_22",
                "divisions\\d_23",
                "divisions\\d_24",
                "divisions\\d_25",
                "divisions\\d_26",
                "divisions\\d_27",
                "divisions\\d_28",
                "divisions\\d_29",
                "divisions\\d_30",
                "divisions\\d_31",
                "divisions\\d_32",
                "divisions\\d_33",
                "divisions\\d_34",
                "divisions\\d_35",
                "divisions\\d_36",
                "divisions\\d_37",
                "divisions\\d_38",
                "divisions\\d_39",
                "divisions\\d_40",
                "divisions\\d_41",
                "divisions\\d_42",
                "divisions\\d_43",
                "divisions\\d_44",
                "divisions\\d_45",
                "divisions\\d_46",
                "divisions\\d_47",
                "divisions\\d_48",
                "divisions\\d_49",
                "divisions\\d_50",
                "divisions\\d_51",
                "divisions\\d_52",
                "divisions\\d_53",
                "divisions\\d_54",
                "divisions\\d_55",
                "divisions\\d_56",
                "divisions\\d_57",
                "divisions\\d_58",
                "divisions\\d_59",
                "divisions\\d_60",
                "divisions\\d_61",
                "divisions\\d_62",
                "divisions\\d_63",
                "divisions\\d_64",
                "divisions\\d_65",
                "divisions\\d_66",
                "divisions\\d_67",
                "divisions\\d_68",
                "divisions\\d_69",
                "divisions\\d_70",
                "divisions\\d_71",
                "divisions\\d_72",
                "divisions\\d_73",
                "divisions\\d_74",
                "divisions\\d_75",
                "divisions\\d_76",
                "divisions\\d_77",
                "divisions\\d_78",
                "divisions\\d_79",
                "divisions\\d_80",
                "divisions\\d_81",
                "divisions\\d_82",
                "divisions\\d_83",
                "divisions\\d_84",
                "divisions\\d_85",
                "divisions\\d_86",
                "divisions\\d_87",
                "divisions\\d_88",
                "divisions\\d_89",
                "divisions\\d_90",
                "divisions\\d_91",
                "divisions\\d_92",
                "divisions\\d_93",
                "divisions\\d_94",
                "divisions\\d_95",
                "divisions\\d_96",
                "divisions\\d_97",
                "divisions\\d_98",
                "divisions\\d_99",
                "brigades\\none.txt",
                "brigades\\artillery.txt",
                "brigades\\sp_artillery.txt",
                "brigades\\rocket_artillery.txt",
                "brigades\\sp_rct_artillery.txt",
                "brigades\\anti_tank.txt",
                "brigades\\tank_destroyer.txt",
                "brigades\\light_armor_brigade.txt",
                "brigades\\heavy_armor.txt",
                "brigades\\super_heavy_armor.txt",
                "brigades\\armored_car.txt",
                "brigades\\anti_air.txt",
                "brigades\\police.txt",
                "brigades\\engineer.txt",
                "brigades\\cag.txt",
                "brigades\\escort.txt",
                "brigades\\naval_asw.txt",
                "brigades\\naval_anti_air_s.txt",
                "brigades\\naval_radar_s.txt",
                "brigades\\naval_fire_controll_s.txt",
                "brigades\\naval_improved_hull_s.txt",
                "brigades\\naval_torpedoes_s.txt",
                "brigades\\naval_anti_air_l.txt",
                "brigades\\naval_radar_l.txt",
                "brigades\\naval_fire_controll_l.txt",
                "brigades\\naval_improved_hull_l.txt",
                "brigades\\naval_torpedoes_l.txt",
                "brigades\\b_u1.txt",
                "brigades\\b_u2.txt",
                "brigades\\b_u3.txt",
                "brigades\\b_u4.txt",
                "brigades\\b_u5.txt",
                "brigades\\b_u6.txt",
                "brigades\\b_u7.txt",
                "brigades\\b_u8.txt",
                "brigades\\b_u9.txt",
                "brigades\\b_u10.txt",
                "brigades\\b_u11.txt",
                "brigades\\b_u12.txt",
                "brigades\\b_u13.txt",
                "brigades\\b_u14.txt",
                "brigades\\b_u15.txt",
                "brigades\\b_u16.txt",
                "brigades\\b_u17.txt",
                "brigades\\b_u18.txt",
                "brigades\\b_u19.txt",
                "brigades\\b_u20.txt",
                "brigades\\cavalry_brigade.txt.txt",
                "brigades\\sp_anti_air.txt",
                "brigades\\medium_armor.txt",
                "brigades\\floatplane.txt",
                "brigades\\light_cag.txt",
                "brigades\\amph_armor.txt",
                "brigades\\glider_armor.txt",
                "brigades\\glider_artillery.txt",
                "brigades\\super_heavy_artillery.txt",
                "brigades\\b_rsv_36.txt",
                "brigades\\b_rsv_37.txt",
                "brigades\\b_rsv_38.txt",
                "brigades\\b_rsv_39.txt",
                "brigades\\b_rsv_40.txt",
                "brigades\\b_01.txt",
                "brigades\\b_02.txt",
                "brigades\\b_03.txt",
                "brigades\\b_04.txt",
                "brigades\\b_05.txt",
                "brigades\\b_06.txt",
                "brigades\\b_07.txt",
                "brigades\\b_08.txt",
                "brigades\\b_09.txt",
                "brigades\\b_10.txt",
                "brigades\\b_11.txt",
                "brigades\\b_12.txt",
                "brigades\\b_13.txt",
                "brigades\\b_14.txt",
                "brigades\\b_15.txt",
                "brigades\\b_16.txt",
                "brigades\\b_17.txt",
                "brigades\\b_18.txt",
                "brigades\\b_19.txt",
                "brigades\\b_20.txt",
                "brigades\\b_21.txt",
                "brigades\\b_22.txt",
                "brigades\\b_23.txt",
                "brigades\\b_24.txt",
                "brigades\\b_25.txt",
                "brigades\\b_26.txt",
                "brigades\\b_27.txt",
                "brigades\\b_28.txt",
                "brigades\\b_29.txt",
                "brigades\\b_30.txt",
                "brigades\\b_31.txt",
                "brigades\\b_32.txt",
                "brigades\\b_33.txt",
                "brigades\\b_34.txt",
                "brigades\\b_35.txt",
                "brigades\\b_36.txt",
                "brigades\\b_37.txt",
                "brigades\\b_38.txt",
                "brigades\\b_39.txt",
                "brigades\\b_40.txt",
                "brigades\\b_41.txt",
                "brigades\\b_42.txt",
                "brigades\\b_43.txt",
                "brigades\\b_44.txt",
                "brigades\\b_45.txt",
                "brigades\\b_46.txt",
                "brigades\\b_47.txt",
                "brigades\\b_48.txt",
                "brigades\\b_49.txt",
                "brigades\\b_50.txt",
                "brigades\\b_51.txt",
                "brigades\\b_52.txt",
                "brigades\\b_53.txt",
                "brigades\\b_54.txt",
                "brigades\\b_55.txt",
                "brigades\\b_56.txt",
                "brigades\\b_57.txt",
                "brigades\\b_58.txt",
                "brigades\\b_59.txt",
                "brigades\\b_60.txt",
                "brigades\\b_61.txt",
                "brigades\\b_62.txt",
                "brigades\\b_63.txt",
                "brigades\\b_64.txt",
                "brigades\\b_65.txt",
                "brigades\\b_66.txt",
                "brigades\\b_67.txt",
                "brigades\\b_68.txt",
                "brigades\\b_69.txt",
                "brigades\\b_70.txt",
                "brigades\\b_71.txt",
                "brigades\\b_72.txt",
                "brigades\\b_73.txt",
                "brigades\\b_74.txt",
                "brigades\\b_75.txt",
                "brigades\\b_76.txt",
                "brigades\\b_77.txt",
                "brigades\\b_78.txt",
                "brigades\\b_79.txt",
                "brigades\\b_80.txt",
                "brigades\\b_81.txt",
                "brigades\\b_82.txt",
                "brigades\\b_83.txt",
                "brigades\\b_84.txt",
                "brigades\\b_85.txt",
                "brigades\\b_86.txt",
                "brigades\\b_87.txt",
                "brigades\\b_88.txt",
                "brigades\\b_89.txt",
                "brigades\\b_90.txt",
                "brigades\\b_91.txt",
                "brigades\\b_92.txt",
                "brigades\\b_93.txt",
                "brigades\\b_94.txt",
                "brigades\\b_95.txt",
                "brigades\\b_96.txt",
                "brigades\\b_97.txt",
                "brigades\\b_98.txt",
                "brigades\\b_99.txt"
            };

        /// <summary>
        ///     ユニットの兵科とIDの対応付け
        /// </summary>
        public static readonly Dictionary<UnitType, UnitBranch> BranchMap = new Dictionary<UnitType, UnitBranch>();

        /// <summary>
        ///     デフォルトの兵科
        /// </summary>
        private static readonly UnitBranch[] DefaultBranches =
            {
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.AirDivision,
                UnitBranch.AirDivision,
                UnitBranch.AirDivision,
                UnitBranch.AirDivision,
                UnitBranch.AirDivision,
                UnitBranch.AirDivision,
                UnitBranch.AirDivision,
                UnitBranch.NavalDivision,
                UnitBranch.NavalDivision,
                UnitBranch.NavalDivision,
                UnitBranch.NavalDivision,
                UnitBranch.NavalDivision,
                UnitBranch.NavalDivision,
                UnitBranch.NavalDivision,
                UnitBranch.NavalDivision,
                UnitBranch.AirDivision,
                UnitBranch.AirDivision,
                UnitBranch.LandDivision,
                UnitBranch.AirDivision,
                UnitBranch.NavalDivision,
                UnitBranch.NavalDivision,
                UnitBranch.AirDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandDivision,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.NavalBrigade,
                UnitBranch.AirBrigade,
                UnitBranch.NavalBrigade,
                UnitBranch.NavalBrigade,
                UnitBranch.NavalBrigade,
                UnitBranch.NavalBrigade,
                UnitBranch.NavalBrigade,
                UnitBranch.NavalBrigade,
                UnitBranch.NavalBrigade,
                UnitBranch.NavalBrigade,
                UnitBranch.NavalBrigade,
                UnitBranch.NavalBrigade,
                UnitBranch.NavalBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.NavalBrigade,
                UnitBranch.NavalBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade,
                UnitBranch.LandBrigade
            };

        /// <summary>
        ///     編集済みフラグ
        /// </summary>
        private static readonly bool[] Dirty = new bool[Enum.GetValues(typeof (UnitType)).Length];

        /// <summary>
        ///     読み込み済みフラグ
        /// </summary>
        private static bool _loaded;

        /// <summary>
        ///     静的コンストラクタ
        /// </summary>
        static Units()
        {
            // ユニット文字列とIDの対応付けを初期化
            foreach (UnitType type in Enum.GetValues(typeof (UnitType)))
            {
                StringMap.Add(StringTable[(int) type], type);
            }
        }

        /// <summary>
        ///     ユニット定義ファイル群を読み込む
        /// </summary>
        public static void Load()
        {
            // 読み込み済みならば戻る
            if (_loaded)
            {
                return;
            }

            InitUnitTable();
            InitFileNames();
            InitBranches();

            List.Clear();
            foreach (UnitType type in UnitTable)
            {
                try
                {
                    LoadFile(type);
                }
                catch (Exception)
                {
                    string fileName = Game.GetFileName(Path.Combine(Game.UnitPathName, FileNameMap[type]));
                    MessageBox.Show(String.Format("{0}: {1}", Resources.FileReadError, fileName), Resources.Error);
                }
            }

            _loaded = true;
        }

        /// <summary>
        ///     ユニット定義ファイルを読み込む
        /// </summary>
        /// <param name="type">ユニットの種類</param>
        private static void LoadFile(UnitType type)
        {
            string fileName = Game.GetFileName(Path.Combine(Game.UnitPathName, FileNameMap[type]));
            Unit unit = UnitParser.Parse(fileName, BranchMap[type]);
            List.Add(unit);
            SetDirty(type, false);
        }

        /// <summary>
        ///     ユニット定義ファイル群を保存する
        /// </summary>
        public static void Save()
        {
            string folderName = Path.Combine(Game.IsModActive ? Game.ModFolderName : Game.FolderName, Game.UnitPathName);
            // フォルダがなければ作成する
            if (!Directory.Exists(folderName))
            {
                Directory.CreateDirectory(folderName);
            }

            foreach (Unit unit in List)
            {
                if (Dirty[(int) unit.Type])
                {
                    string fileName = Path.Combine(folderName, FileNameMap[unit.Type]);
                    try
                    {
                        UnitWriter.Write(unit, fileName);
                        SetDirty(unit.Type, false);
                    }
                    catch (Exception)
                    {
                        MessageBox.Show(String.Format("{0}: {1}", Resources.FileWriteError, fileName), Resources.Error);
                    }
                }
            }
        }

        /// <summary>
        ///     ユニット一覧を初期化する
        /// </summary>
        private static void InitUnitTable()
        {
            if (Game.Type == GameType.ArsenalOfDemocracy)
            {
                UnitTable = UnitTableAoD;
            }
            else if (Game.Type == GameType.DarkestHour && Game.Version >= 103)
            {
                UnitTable = UnitTableDh;
            }
            else
            {
                UnitTable = UnitTableHoI2;
            }
        }

        /// <summary>
        ///     ユニット定義ファイル一覧を初期化する
        /// </summary>
        private static void InitFileNames()
        {
            FileNameMap.Clear();
            foreach (UnitType type in UnitTable)
            {
                FileNameMap.Add(type, DefaultFileNames[(int) type]);
            }
        }

        /// <summary>
        ///     ユニットの兵科を初期化する
        /// </summary>
        private static void InitBranches()
        {
            BranchMap.Clear();
            foreach (UnitType type in UnitTable)
            {
                BranchMap.Add(type, DefaultBranches[(int) type]);
            }
        }

        /// <summary>
        ///     ファイルの再読み込みを要求する
        /// </summary>
        public static void RequireReload()
        {
            _loaded = false;
        }

        /// <summary>
        ///     編集済みフラグを更新する
        /// </summary>
        /// <param name="type">ユニットの種類</param>
        /// <param name="flag">フラグ状態</param>
        public static void SetDirty(UnitType type, bool flag)
        {
            Dirty[(int) type] = flag;
        }
    }
}