//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18052
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoI2Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HoI2Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Airforce に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BranchAirforce {
            get {
                return ResourceManager.GetString("BranchAirforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Army に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BranchArmy {
            get {
                return ResourceManager.GetString("BranchArmy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Navy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BranchNavy {
            get {
                return ResourceManager.GetString("BranchNavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amphibious Light Armor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrigadeAmphibiousLightArmor {
            get {
                return ResourceManager.GetString("BrigadeAmphibiousLightArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anti-tank Brigade に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrigadeAntiTank {
            get {
                return ResourceManager.GetString("BrigadeAntiTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cavalry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrigadeCavalry {
            get {
                return ResourceManager.GetString("BrigadeCavalry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Floatplane に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrigadeFloatPlane {
            get {
                return ResourceManager.GetString("BrigadeFloatPlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light Glider Armor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrigadeGliderLightArmor {
            get {
                return ResourceManager.GetString("BrigadeGliderLightArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light Glider Artillery に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrigadeGliderLightArtillery {
            get {
                return ResourceManager.GetString("BrigadeGliderLightArtillery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light Carrier Air Group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrigadeLightCarrierAirGroup {
            get {
                return ResourceManager.GetString("BrigadeLightCarrierAirGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Medium-tank Brigade に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrigadeMediumTank {
            get {
                return ResourceManager.GetString("BrigadeMediumTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capital Torpedoes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrigadeNavalTorpedoesL {
            get {
                return ResourceManager.GetString("BrigadeNavalTorpedoesL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrigadeNone {
            get {
                return ResourceManager.GetString("BrigadeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reserved Brigade  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrigadeReserved {
            get {
                return ResourceManager.GetString("BrigadeReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rocket Artillery に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrigadeRocketArtillery {
            get {
                return ResourceManager.GetString("BrigadeRocketArtillery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Self-Propelled Anti-aircraft に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrigadeSpAntiAir {
            get {
                return ResourceManager.GetString("BrigadeSpAntiAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Self-Propelled Rocket Artillery に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrigadeSpRocketArtillery {
            get {
                return ResourceManager.GetString("BrigadeSpRocketArtillery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Super Heavy Artillery に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrigadeSuperHeavyArtillery {
            get {
                return ResourceManager.GetString("BrigadeSuperHeavyArtillery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Brigade  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrigadeUser {
            get {
                return ResourceManager.GetString("BrigadeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The items has been changed. Do you want to save the changes? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmSaveMessage {
            get {
                return ResourceManager.GetString("ConfirmSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Atlantic Ocean に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContinentAtlanticOcean {
            get {
                return ResourceManager.GetString("ContinentAtlanticOcean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indian Ocean に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContinentIndianOcean {
            get {
                return ResourceManager.GetString("ContinentIndianOcean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lake に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContinentLake {
            get {
                return ResourceManager.GetString("ContinentLake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pacific Ocean に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContinentPacificOcean {
            get {
                return ResourceManager.GetString("ContinentPacificOcean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light Carrier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivisionLightCarrier {
            get {
                return ResourceManager.GetString("DivisionLightCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reserved Division  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivisionReserved {
            get {
                return ResourceManager.GetString("DivisionReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rocket Interceptors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivisionRocketInterceptor {
            get {
                return ResourceManager.GetString("DivisionRocketInterceptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Division  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivisionUser {
            get {
                return ResourceManager.GetString("DivisionUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading file error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileReadError {
            get {
                return ResourceManager.GetString("FileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Writing file error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileWriteError {
            get {
                return ResourceManager.GetString("FileWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hitler に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hitler {
            get {
                return ResourceManager.GetString("Hitler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid AA position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidAaPosition {
            get {
                return ResourceManager.GetString("InvalidAaPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid area name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidArea {
            get {
                return ResourceManager.GetString("InvalidArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid army position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidArmyPosition {
            get {
                return ResourceManager.GetString("InvalidArmyPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid beach に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidBeach {
            get {
                return ResourceManager.GetString("InvalidBeach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid beach icon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidBeachIcon {
            get {
                return ResourceManager.GetString("InvalidBeachIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid beach position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidBeachPosition {
            get {
                return ResourceManager.GetString("InvalidBeachPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid branch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidBranch {
            get {
                return ResourceManager.GetString("InvalidBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid city position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidCityPosition {
            get {
                return ResourceManager.GetString("InvalidCityPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid climate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidClimate {
            get {
                return ResourceManager.GetString("InvalidClimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid continent name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidContinent {
            get {
                return ResourceManager.GetString("InvalidContinent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid counter position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidCounterPosition {
            get {
                return ResourceManager.GetString("InvalidCounterPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid country tag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidCountryTag {
            get {
                return ResourceManager.GetString("InvalidCountryTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid end year に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidEndYear {
            get {
                return ResourceManager.GetString("InvalidEndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid energy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidEnergy {
            get {
                return ResourceManager.GetString("InvalidEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid experience に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidExperience {
            get {
                return ResourceManager.GetString("InvalidExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid filling position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidFillPosition {
            get {
                return ResourceManager.GetString("InvalidFillPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid fort position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidFortPosition {
            get {
                return ResourceManager.GetString("InvalidFortPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid IC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidIc {
            get {
                return ResourceManager.GetString("InvalidIc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidID {
            get {
                return ResourceManager.GetString("InvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid ideal rank に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidIdealRank {
            get {
                return ResourceManager.GetString("InvalidIdealRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid ideology に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidIdeology {
            get {
                return ResourceManager.GetString("InvalidIdeology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid infrastructure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidInfrastructure {
            get {
                return ResourceManager.GetString("InvalidInfrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid loyalty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidLoyalty {
            get {
                return ResourceManager.GetString("InvalidLoyalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid manpower に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidManpower {
            get {
                return ResourceManager.GetString("InvalidManpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid max skill に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidMaxSkill {
            get {
                return ResourceManager.GetString("InvalidMaxSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid metal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidMetal {
            get {
                return ResourceManager.GetString("InvalidMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid oil に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidOil {
            get {
                return ResourceManager.GetString("InvalidOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid minister personality に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidPersonality {
            get {
                return ResourceManager.GetString("InvalidPersonality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid port に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidPort {
            get {
                return ResourceManager.GetString("InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid port position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidPortPosition {
            get {
                return ResourceManager.GetString("InvalidPortPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid port seazone に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidPortSeazone {
            get {
                return ResourceManager.GetString("InvalidPortSeazone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid minister position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidPosition {
            get {
                return ResourceManager.GetString("InvalidPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid rank year に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidRankYear {
            get {
                return ResourceManager.GetString("InvalidRankYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid rare materials に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidRareMaterials {
            get {
                return ResourceManager.GetString("InvalidRareMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid region name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidRegion {
            get {
                return ResourceManager.GetString("InvalidRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid retirement year に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidRetirementYear {
            get {
                return ResourceManager.GetString("InvalidRetirementYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid skill に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidSkill {
            get {
                return ResourceManager.GetString("InvalidSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid tech speciality に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidSpeciality {
            get {
                return ResourceManager.GetString("InvalidSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid start year に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidStartYear {
            get {
                return ResourceManager.GetString("InvalidStartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid terrain に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidTerrain {
            get {
                return ResourceManager.GetString("InvalidTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid token に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid token count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidTokenCount {
            get {
                return ResourceManager.GetString("InvalidTokenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid leader traits に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidTraits {
            get {
                return ResourceManager.GetString("InvalidTraits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeySelectAll {
            get {
                return ResourceManager.GetString("KeySelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyUnselectAll {
            get {
                return ResourceManager.GetString("KeyUnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Label に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extra1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageExtra1 {
            get {
                return ResourceManager.GetString("LanguageExtra1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extra2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageExtra2 {
            get {
                return ResourceManager.GetString("LanguageExtra2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Français に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageFrench {
            get {
                return ResourceManager.GetString("LanguageFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deutsch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageGerman {
            get {
                return ResourceManager.GetString("LanguageGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Italiano に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageItalian {
            get {
                return ResourceManager.GetString("LanguageItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageJapanese {
            get {
                return ResourceManager.GetString("LanguageJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Polski に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguagePolish {
            get {
                return ResourceManager.GetString("LanguagePolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Português に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguagePortuguese {
            get {
                return ResourceManager.GetString("LanguagePortuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Русский に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageRussian {
            get {
                return ResourceManager.GetString("LanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Español に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageSpanish {
            get {
                return ResourceManager.GetString("LanguageSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoyaltyHigh {
            get {
                return ResourceManager.GetString("LoyaltyHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoyaltyLow {
            get {
                return ResourceManager.GetString("LoyaltyLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Medium に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoyaltyMedium {
            get {
                return ResourceManager.GetString("LoyaltyMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NA に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoyaltyNA {
            get {
                return ResourceManager.GetString("LoyaltyNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undying に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoyaltyUndying {
            get {
                return ResourceManager.GetString("LoyaltyUndying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Very High に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoyaltyVeryHigh {
            get {
                return ResourceManager.GetString("LoyaltyVeryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Very Low に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoyaltyVeryLow {
            get {
                return ResourceManager.GetString("LoyaltyVeryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified minister personality に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModifiedPersonality {
            get {
                return ResourceManager.GetString("ModifiedPersonality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bitmap (*.bmp)|*.bmp|All files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenBitmapFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenBitmapFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a game folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenGameFolderDialogDescription {
            get {
                return ResourceManager.GetString("OpenGameFolderDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a MOD folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenModFolderDialogDescription {
            get {
                return ResourceManager.GetString("OpenModFolderDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parse failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParseFailed {
            get {
                return ResourceManager.GetString("ParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Marshal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank0 {
            get {
                return ResourceManager.GetString("Rank0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank1 {
            get {
                return ResourceManager.GetString("Rank1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lieutenant General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank2 {
            get {
                return ResourceManager.GetString("Rank2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Major General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank3 {
            get {
                return ResourceManager.GetString("Rank3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   section に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Airborne Training に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialityAirborneTraining {
            get {
                return ResourceManager.GetString("SpecialityAirborneTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avionics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialityAvionics {
            get {
                return ResourceManager.GetString("SpecialityAvionics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blitzkrieg Tactics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialityBlitzkriegTactics {
            get {
                return ResourceManager.GetString("SpecialityBlitzkriegTactics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bomber Design に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialityBomberDesign {
            get {
                return ResourceManager.GetString("SpecialityBomberDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Carrier Design に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialityCarrierDesign {
            get {
                return ResourceManager.GetString("SpecialityCarrierDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cavalry Tactics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialityCavalryTactics {
            get {
                return ResourceManager.GetString("SpecialityCavalryTactics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fighter Design に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialityFighterDesign {
            get {
                return ResourceManager.GetString("SpecialityFighterDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maneuver Tactics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialityManeuverTactics {
            get {
                return ResourceManager.GetString("SpecialityManeuverTactics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Marine Training に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialityMarineTraining {
            get {
                return ResourceManager.GetString("SpecialityMarineTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Medical Science に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialityMedicine {
            get {
                return ResourceManager.GetString("SpecialityMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mountain Training に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialityMountainTraining {
            get {
                return ResourceManager.GetString("SpecialityMountainTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Munitions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialityMunitions {
            get {
                return ResourceManager.GetString("SpecialityMunitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Static Defense Tactics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialityStaticDefenseTactics {
            get {
                return ResourceManager.GetString("SpecialityStaticDefenseTactics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submarine Design に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialitySubmarineDesign {
            get {
                return ResourceManager.GetString("SpecialitySubmarineDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Tech Speciality  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialityUser {
            get {
                return ResourceManager.GetString("SpecialityUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vehicle Engineering に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialityVehicleEngineering {
            get {
                return ResourceManager.GetString("SpecialityVehicleEngineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stalin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stalin {
            get {
                return ResourceManager.GetString("Stalin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   World に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
