//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18010
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoI2Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HoI2Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (陸軍) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Army {
            get {
                return ResourceManager.GetString("Army", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (ヒトラー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hitler {
            get {
                return ResourceManager.GetString("Hitler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効なトークン: {0}
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeySelectAll {
            get {
                return ResourceManager.GetString("KeySelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全解除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyUnselectAll {
            get {
                return ResourceManager.GetString("KeyUnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (海軍) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Navy {
            get {
                return ResourceManager.GetString("Navy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビットマップ (*.bmp)|*.bmp|すべてのファイル (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenBitmapFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenBitmapFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲームフォルダを選択して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenGameFolderDialogDescription {
            get {
                return ResourceManager.GetString("OpenGameFolderDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MODフォルダを選択して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenModFolderDialogDescription {
            get {
                return ResourceManager.GetString("OpenModFolderDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解析失敗: {0}
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParseFailed {
            get {
                return ResourceManager.GetString("ParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解析失敗: {0}セクション / {1}
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParseFailedSection {
            get {
                return ResourceManager.GetString("ParseFailedSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (スターリン) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stalin {
            get {
                return ResourceManager.GetString("Stalin", resourceCulture);
            }
        }
    }
}
